### ISSUE TITLE
Docker Deployment Action

### ISSUE THREAD

**Issue by oke-aditya** [airctic/icevision#127]
## 🐛 Bug
**Describe the bug**
- It is a very simple bug, a good first MLOps issue. It will be fixed anyways soon.
- The docker action for GitHub is not building on branch docker_deploy.
- If someone can test locally and fix up the docker action in .github folder great.

Note Dockerfile is already made which is correct as it build locally. Its a very small issue of GitHub action.

Something simple to get deployment contribution.

#99 Also refer #113

**Comment by oke-aditya** [comment]
Just keeping here so that we don't forget about it. It should be solved before first release

**Comment by adamfarquhar** [comment]
A docker pull request results in an error and the docker images appear to be > 2 months old (as of 25-Aug). Suggest that until this issue is fixed, the documentation is removed or flagged as not working. 

docker pull mantisshrimp
Using default tag: latest
Error response from daemon: pull access denied for mantisshrimp, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by oke-aditya** [comment]
True @adamfarquhar we have not updated the docker container. 
Hopefully we will fix it with CI action. Docker container has to support GPU Training and that's what we need to confirm, plus we need to bundle soft dependencies as well.
@ai-fast-track can we edit the docs for this ?
