### ISSUE TITLE
show_record sometimes truncates the label

### ISSUE THREAD

**Issue by adamfarquhar** [airctic/icevision#392]
## 🐛 Bug
**Describe the bug**
If the bbox goes to the top of an image, show_record doesn't show the label. This shows in the getting started tutorial.

show_record(train_records[1])

![image](https://user-images.githubusercontent.com/454453/92532193-ab4fc700-f227-11ea-8787-b005bfeeaced.png)

**Comment by lgvaz** [comment]
Definitely a bug. We recently updated all our show methods to use opencv, good catch!!

Any suggestions on how to handle this? Quite a tricky situation

**Comment by ai-fast-track** [comment]
One way to do it is to test if the label has negative y-coordinates (meaning a part of the box is outside the image) is to draw the label box inside the bbox: That label box is in fact the mirror of the regular label box. Therefore, when calculating the offset of label box we just have to the do the opposite operation: instead of subtracting the y-offset, we add the y-offset (so the label box will be drawn inside the bbox)
