### ISSUE TITLE
Add progress bar for record parser Autofix 

### ISSUE THREAD

**Issue by potipot** [airctic/icevision#632]
Apart from regular autofix output, one could consider adding a progress bar for it.

**Comment by lgvaz** [comment]
Seems like a good addition!

We only need to be careful so that the bar and outputs don't mess with each other. We can use the parameter `show_pbar` that is passed to `Parser.parse` to decide whether or not to show the bar on autofix.

If you're interested in implementing this I can assign this issue to you

**Comment by FraPochetti** [comment]
Not relevant.
