### ISSUE TITLE
Some traces of cv2 remain

### ISSUE THREAD

**Issue by robmarkcole** [airctic/icevision#809]
## 🐛 Bug
In 0.7.0 cv2 has been removed yet a couple of traces remain https://github.com/airctic/icevision/search?q=cv2

This may cause import errors

**Comment by rsomani95** [comment]
I think the `albumentations` part cannot be removed as it's that lib requires `cv2`

**Comment by lgvaz** [comment]
But we can remove `albumentations` from the minimal requirements and add it to `all`.

What we really need to change is the function `open_img` to use PIL instead of cv2

**Comment by rsomani95** [comment]
@lgvaz That should be straightforward? Do you know if cv2 converts to RGB? Or maybe `open_img` already takes an arg for input namespace?

**Comment by lgvaz** [comment]
> That should be straightforward?
Yes (I'm actually going insane, because I swear I've done this before)... ACTUALLY, I'm going insane! Check [here](https://github.com/airctic/icevision/blob/master/icevision/utils/imageio.py#L16)

I was checking vscode and it was opening an outdated file under `/build`, what

**Comment by lgvaz** [comment]
Okaaaay, much easier than, it seems these are the only traces left:
![image](https://user-images.githubusercontent.com/16520544/115869551-6b370080-a414-11eb-81be-9f0334d2bc54.png)

And since albumentations is a soft dependency, we can be sure that if the user tries to use it, opencv will be installed

**Comment by FraPochetti** [comment]
Resolved.
