### ISSUE TITLE
Integrate YOLO

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#91]
## 🚀 Feature
Adds support for training YOLO. 

This can be a good experience to understand if we only need a model hub or something like we currently have for detr (where we use all their source code).

YOLO v5 is available [here](https://github.com/lgvaz/yolov5)

**Comment by oke-aditya** [comment]
We would need a model hub and core API. 
Suppose some researcher tomorrow comes up with slight modification of YOLO. We can't edit it on hub right ? Since hub is community maintained. 

But yes we can edit in Core API as it is maintained by us.

Making a new hub module for adding a small new edit (e.g. backbone change, init change or layer change) would be something inefficient. But making edit to make Core API more SOTA is better.

**Comment by lgvaz** [comment]
closed in favor of #506
