### ISSUE TITLE
Refactor reading of image size for coco parser

### ISSUE THREAD

**Issue by fstroth** [airctic/icevision#918]
https://github.com/airctic/icevision/blob/871636277bdd84aca1002b532fcb97e595987af8/icevision/parsers/coco_parser.py#L80

It is faster to just read the image size from the coco data instead of touching the file on disk.

```python
def img_size(self, o) -> ImgSize:
        return (self._record_id2info[o["image_id"]]["width"],  self._record_id2info[o["image_id"]]["height"])
```

Will create PR for this later.

**Comment by lgvaz** [comment]
We came back and forth on this for long. A recurrent issue is that sometimes the image size on the annotation is wrong (almost always due to EXIF flags on the image), so we opted for the default to read the image size from disk.

maybe we can add an extra section on the documentation, talking about this and how to read directly from the annotations?

**Comment by FraPochetti** [comment]
@fstroth can we close this one?
